language: erlang
otp_release:
  - 17.0
  - 17.1
install: mix deps.get
before_install:
  - mkdir -p vendor/elixir
  - wget -q http://s3.hex.pm/builds/elixir/stable.zip && unzip -qq stable.zip -d vendor/elixir
  - export PATH="$PATH:$PWD/vendor/elixir/bin"
  - export MIX_ENV=test
  - mix local.hex --force
script: mix test
services:
 - elasticsearch
notifications:
  irc: "irc.freenode.net#funnel"
